### PR TITLE
rename generate_config to google_cloud_ops_agent_engine for clarity

### PR DESCRIPTION
**Pull request by ekund**
Error messages will then reference the more aptly-named "google_cloud_ops_agent_engine" binary.

### CODE REVIEW

**Review by davidbtucker — APPROVED** [review]

**Comment by igorpeshansky** [comment]
[Optional] Why not `google_cloud_ops_agent_config_generator`? Also, the bike shed should be blue. 😁

**Comment by davidbtucker** [comment]
> [Optional] Why not `google_cloud_ops_agent_config_generator`? Also, the bike shed should be blue. 😁

The "Ops Agent Engine" terminology came from Joe, so you could discuss with him.

**Comment by quentinmit** [comment]
I'm definitely more confused by this new name. "engine" implies a daemon and this process is not. We certainly might have something in the future that deserves this name, but the config generator ain't it...

**Comment by quentinmit** [comment]
Hi, I'm not going to forget about this. This PR still makes no sense. :)

**Pull request merged**
