### PR TITLE
Makefile: create Makefile

### PR DESCRIPTION
**Pull request by braydonk**
I got tired of typing these commands out, so thought it wouldn't hurt to
get a Makefile started.

### CODE REVIEW

**Comment by igorpeshansky** [comment]
I thought we used the `Dockerfile` as a replacement for a `Makefile`, but I'll let @quentinmit comment…

**Comment by qingling128** [comment]
Having these for convenience should be fine I think. Can we add a declamation / notice / comment to make it clear that this is for internal development convenience and are subject to changes without further notice. So that customers don't build dependencies on them. Or they can do so but with known risks that we might change / remove the interface in the future.

**Comment by braydonk** [comment]
Makefile here is meant mostly as a way to run common tasks with `make` tags and not meant for actually building. We could try another tool for running these sorts of things (i.e. [tusk](https://github.com/rliebz/tusk)) but `make` is pretty ubiquitous for this in other Go projects (including across OpenTelemetry repos). I can add a comment to the top of the Makefile that signifies that it is meant for running tasks in Development and not for production/release builds.

**Review by qingling128 — APPROVED** [review]
LGTM modulo some disclamation / comment is added as mentioned above.

**Pull request merged**
