### PR TITLE
Temporarily pin Golang at 1.14 for sles 12.

### PR DESCRIPTION
**Pull request by qingling128**
Temporary workaround for b/182517088#comment14.

### CODE REVIEW

**Comment by qingling128** [comment]
Looks like Xenial is pinned to Golang 1.11. I thought about unifying everything to Golang 1.14, then I saw that and figured there was probably some reason.

**Comment by quentinmit** [comment]
The commit message is misleading - as far as we know there is no upstream repo problem, only a zypper bug :)

**Comment by qingling128** [comment]
> The commit message is misleading - as far as we know there is no upstream repo problem, only a zypper bug :)

I wonder why it is only related to Golang and the problem started when the new Golang 1.16 package was released. I'm not sure whether it's the Go package issue or Zypper issue. But I rephrased the title just in case.

**Comment by quentinmit** [comment]
> > The commit message is misleading - as far as we know there is no upstream repo problem, only a zypper bug :)
> 
> I wonder why it is only related to Golang and the problem started when the new Golang 1.16 package was released. I'm not sure whether it's the Go package issue or Zypper issue. But I rephrased the title just in case.

No matter how broken or not the package or repo are, Zypper segfaulting is entirely on Zypper. :)

**Comment by qingling128** [comment]
> No matter how broken or not the package or repo are, Zypper segfaulting is entirely on Zypper. :)

Ah I see. Good to know.

**Review by davidbtucker — APPROVED** [review]

**Pull request merged**
