### PR TITLE
Use a tomcat archive version instead of latest version cdn to fix flaky tests and extend the default log file paths.

### PR DESCRIPTION
**Pull request by dehaansa**
Where the previous temporary fix fixed tests, this one points at a repository that appears to not only be latest version & won't require updating intermittently.

### CODE REVIEW

**Comment by qingling128** [comment]
Looks like the tests were not kicked off. So bumping it.

**Comment by qingling128** [comment]
Looks like the build failed:

```
#127 4666.7 
#127 4666.7 > Task :jmx-metrics:compileGroovy
#127 4666.7 warning: Implicitly compiled files were not subject to annotation processing.
#127 4666.7   Use -implicit to specify a policy for implicit compilation.
#127 4666.7 1 warning
#127 4667.0 
#127 4667.0 > Task :jmx-metrics:processResources
#127 4667.0 > Task :jmx-metrics:classes
#127 4667.0 > Task :jmx-metrics:jar
#127 4667.5 
#127 4667.5 > Task :jmx-metrics:startScripts
#127 4667.5 Execution optimizations have been disabled for task ':jmx-metrics:startScripts' to ensure correctness due to the following reasons:
#127 4667.5   - Gradle detected a problem with the following location: '/work/submodules/opentelemetry-java-contrib/jmx-metrics/build/libs/opentelemetry-jmx-metrics-1.6.0.jar'. Reason: Task ':jmx-metrics:startScripts' uses this output of task ':jmx-metrics:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
#127 4667.7 
#127 4667.7 > Task :jmx-metrics:distTar
#127 4667.7 Execution optimizations have been disabled for task ':jmx-metrics:distTar' to ensure correctness due to the following reasons:
#127 4667.7   - Gradle detected a problem with the following location: '/work/submodules/opentelemetry-java-contrib/jmx-metrics/build/libs/opentelemetry-jmx-metrics-1.6.0.jar'. Reason: Task ':jmx-metrics:distTar' uses this output of task ':jmx-metrics:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
#127 ...

#95 [centos7-build 7/7] RUN ./pkg/rpm/build.sh
#95 sha256:13683f48127083a75609ecb5fc2a8e9f9dd1a1a1aa0ac98b5bce4b2951453090
#95 CANCELED

#127 [sles15-build 7/7] RUN ./pkg/rpm/build.sh
#127 sha256:a4259c0315e491c30dd6bc4a25ada7e59502d912d7f9c950e0e77a6ed50ab787
#127 CANCELED
------
 > [sles12-build 9/9] RUN ./pkg/rpm/build.sh:
------
------
 > [bionic-build 7/7] RUN ./pkg/deb/build.sh:
------
executor failed running [/bin/sh -c ./pkg/rpm/build.sh]: exit code: 1
```

Might need more investigation.

**Comment by dehaansa** [comment]
> Looks like the build failed:
> 
> ```
> #127 4666.7 
> #127 4666.7 > Task :jmx-metrics:compileGroovy
> #127 4666.7 warning: Implicitly compiled files were not subject to annotation processing.
> #127 4666.7   Use -implicit to specify a policy for implicit compilation.
> #127 4666.7 1 warning
> #127 4667.0 
> #127 4667.0 > Task :jmx-metrics:processResources
> #127 4667.0 > Task :jmx-metrics:classes
> #127 4667.0 > Task :jmx-metrics:jar
> #127 4667.5 
> #127 4667.5 > Task :jmx-metrics:startScripts
> #127 4667.5 Execution optimizations have been disabled for task ':jmx-metrics:startScripts' to ensure correctness due to the following reasons:
> #127 4667.5   - Gradle detected a problem with the following location: '/work/submodules/opentelemetry-java-contrib/jmx-metrics/build/libs/opentelemetry-jmx-metrics-1.6.0.jar'. Reason: Task ':jmx-metrics:startScripts' uses this output of task ':jmx-metrics:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
> #127 4667.7 
> #127 4667.7 > Task :jmx-metrics:distTar
> #127 4667.7 Execution optimizations have been disabled for task ':jmx-metrics:distTar' to ensure correctness due to the following reasons:
> #127 4667.7   - Gradle detected a problem with the following location: '/work/submodules/opentelemetry-java-contrib/jmx-metrics/build/libs/opentelemetry-jmx-metrics-1.6.0.jar'. Reason: Task ':jmx-metrics:distTar' uses this output of task ':jmx-metrics:shadowJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
> #127 ...
> 
> #95 [centos7-build 7/7] RUN ./pkg/rpm/build.sh
> #95 sha256:13683f48127083a75609ecb5fc2a8e9f9dd1a1a1aa0ac98b5bce4b2951453090
> #95 CANCELED
> 
> #127 [sles15-build 7/7] RUN ./pkg/rpm/build.sh
> #127 sha256:a4259c0315e491c30dd6bc4a25ada7e59502d912d7f9c950e0e77a6ed50ab787
> #127 CANCELED
> ------
>  > [sles12-build 9/9] RUN ./pkg/rpm/build.sh:
> ------
> ------
>  > [bionic-build 7/7] RUN ./pkg/deb/build.sh:
> ------
> executor failed running [/bin/sh -c ./pkg/rpm/build.sh]: exit code: 1
> ```
> 
> Might need more investigation.

I believe these are just intermittent failures caused by issues with resources during the build, re-running kokoro to validate.

**Comment by qingling128** [comment]
One test failed: `--- FAIL: TestThirdPartyApps/ops-agent/sles-15/postgresql`. Probably a flake and not related to the Tomcat change here.

The branch is out-of-date though and requires rebasing.

**Review by qingling128 — APPROVED** [review]
LGTM. Needs rebasing before I can merge it though.

**Review by qingling128 — CHANGES_REQUESTED** [review]
Actually, it does not seem like this is needed if https://github.com/GoogleCloudPlatform/ops-agent/pull/344 gets in.

**Comment by Mrod1598** [comment]
> I believe these are just intermittent failures caused by issues with resources during the build, re-running kokoro to validate.

Updated this branch because this one could patch it to allow a release in case my branch ends up needing more work.

**Review by qingling128 — APPROVED** [review]
LGTM

**Pull request merged**
