### PR TITLE
Roll back Couchbase PRs.

### PR DESCRIPTION
**Pull request by qingling128**

### CODE REVIEW

**Comment by sophieyfang** [comment]
LGTM modulo the integration tests pass

**Review by sophieyfang — APPROVED** [review]

**Comment by qingling128** [comment]
Unit and integration tests all passed

**Comment by xhens** [comment]
Hello! I see that you already rolled back the Couchbase PR. Is there a reason for this decision? Are you planning on supporting Couchbase in the future?

**Comment by qingling128** [comment]
@xhens - Hi, yes, https://github.com/GoogleCloudPlatform/ops-agent/pull/695 is the new PR that adds the integration back. The original PR was rolled back because of some infrastructure issue that results in the implementation not fully passing our validation.

**Pull request merged**
