### PR TITLE
Partially revert 476b07de3d594c155594bf0535a8827118b95255

### PR DESCRIPTION
**Pull request by quentinmit**
Igor moved the debian/ directory into a subdirectory to clean up the
root of the repo, but Debian-native packages require that debian/ be at
the root of the repository.

This fixes the generated Debian source packages so that they can
actually be used to rebuild the package (in Debian parlance, the package
FTBF).

This is required if we want to ever potentially upstream this package.

### CODE REVIEW

**Comment by qingling128** [comment]
Is there anything on the build / test / release infra side that we need to change accordingly? I vaguely recall that we had to do `cp pkg/google-cloud-ops-agent*.deb /` to placate Kokoro stuff.

BTW, the automated release pipeline generates agent release notes based on PR commit message. Could we use something a bit more descriptive for the PR title / commit message to be user friendly?

**Comment by quentinmit** [comment]
> Is there anything on the build / test / release infra side that we need to change accordingly? I vaguely recall that we had to do `cp pkg/google-cloud-ops-agent*.deb /` to placate Kokoro stuff.

I don't believe so. That was only needed as a result of the commit I'm reverting. Packages end up at / by default again now.

> BTW, the automated release pipeline generates agent release notes based on PR commit message. Could we use something a bit more descriptive for the PR title / commit message to be user friendly?

How is this new commit message?

**Comment by qingling128** [comment]
The new commit message looks good. I found the PR that might be related: https://github.com/GoogleCloudPlatform/ops-agent/pull/34. @sophieyfang - Could you review this PR to see if the issue you found previous would be affected?

**Comment by sophieyfang** [comment]
> The new commit message looks good. I found the PR that might be related: #34. @sophieyfang - Could you review this PR to see if the issue you found previous would be affected? If packages end up at / by default again now, it should be fine I guess.

One easy way is to test this branch with `./build_and_test_all.sh  branch_name`

**Review by qingling128 — APPROVED** [review]
LGTM

**Comment by sophieyfang** [comment]
Test evidence: https://paste.googleplex.com/4612370975424512

Though the e2e tests failed. i don't think it relates to this PR.

**Comment by quentinmit** [comment]
> Test evidence: https://paste.googleplex.com/4612370975424512
> 
> Though the e2e tests failed. i don't think it relates to this PR.

I agree, those test failures seem unrelated. The package clearly installed correctly on Debian distros.

**Pull request merged**
