### PR TITLE
Update otel to v0.59.1 and not fail when otel UserAgent env not set

### PR DESCRIPTION
**Pull request by sophieyfang**
## Description
Update opentelemetry-operations-collector to latest master branch which includes v0.59.0 and ignore env UserAgent failure in otel agent.

## Related issue
b/243441062

## How has this been tested?
Built an agent with this change then handed it over to client and client verified they no longer have the issues:b/230670850#comment61.
The issue used to be `failed to build environment variables for config: Access is denied`. is due to line https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/0722f29a679287b470ed40e0bb0f6c404362f35e/cmd/otelopscol/main.go#L33 triggered by getUserAgent() in https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/blob/master/internal/env/env.go#L42.

## Checklist:
- Unit tests
  - [x ] Unit tests do not apply.
  - [ ] Unit tests have been added/modified and passed for this PR.
- Integration tests
  - [x ] Integration tests do not apply.
  - [ ] Integration tests have been added/modified and passed for this PR.
- Documentation
  - [x ] This PR introduces no user visible changes.
  - [ ] This PR introduces user visible changes and the corresponding documentation change has been made.
- Minor version bump
  - [ x] This PR introduces no new features.
  - [ ] This PR introduces new features, and there is a separate PR to bump the [minor version](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/VERSION) since the last [release](https://github.com/GoogleCloudPlatform/ops-agent/releases) already.
  - [x ] This PR bumps the version.

### CODE REVIEW

**Comment by schmikei** [comment]
Theorized that the reason the ones that are failing is due to the `transformprocessor` looking into it further but just thought I'd give an update sooner rather than later. The current processor appears to be panicking on all operations as far as I can tell. Looking into it more.

```
{"level":"info","ts":"2022-09-06T12:07:25.807-0400","caller":"service/service.go:129","msg":"Everything is ready. Begin running and processing data."}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x655dfb9]

goroutine 136 [running]:
go.opentelemetry.io/collector/pdata/pmetric.Sum.DataPoints(...)
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector/pdata@v0.59.0/pmetric/generated_metrics.go:843
github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor/internal/metrics.(*Processor).ProcessMetrics(0xc001253270?, {0x10?, 0x83b7040?}, {0xc000c26480?})
	/Users/keithschmitt/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor@v0.59.0/internal/metrics/processor.go:57 +0x259
go.opentelemetry.io/collector/processor/processorhelper.NewMetricsProcessor.func1({0x9db72f0, 0xc000c2a930}, {0xc000c26480?})
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.59.0/processor/processorhelper/metrics.go:75 +0xf8
go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics(...)
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.59.0/consumer/metrics.go:36
go.opentelemetry.io/collector/processor/processorhelper.NewMetricsProcessor.func1({0x9db72f0, 0xc000c2a930}, {0xc000c26480?})
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.59.0/processor/processorhelper/metrics.go:83 +0x1dd
go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics(...)
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.59.0/consumer/metrics.go:36
go.opentelemetry.io/collector/processor/processorhelper.NewMetricsProcessor.func1({0x9db72f0, 0xc000c2a930}, {0x0?})
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.59.0/processor/processorhelper/metrics.go:83 +0x1dd
go.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics(...)
	/Users/keithschmitt/go/pkg/mod/go.opentelemetry.io/collector@v0.59.0/consumer/metrics.go:36
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc000919550)
	/Users/keithschmitt/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.59.0/internal/otlp_transaction.go:160 +0x22a
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1()
	/Users/keithschmitt/go/pkg/mod/github.com/prometheus/prometheus@v0.37.0/scrape/scrape.go:1275 +0x45
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc0001c69a0, {0xedaa9674b?, 0xcfc2fc0?, 0x0?}, {0xedaa9674b?, 0xcfc2fc0?, 0xcfc2fc0?}, 0x0)
	/Users/keithschmitt/go/pkg/mod/github.com/prometheus/prometheus@v0.37.0/scrape/scrape.go:1346 +0xf70
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc0001c69a0, 0xc000369da0?)
	/Users/keithschmitt/go/pkg/mod/github.com/prometheus/prometheus@v0.37.0/scrape/scrape.go:1228 +0x345
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/Users/keithschmitt/go/pkg/mod/github.com/prometheus/prometheus@v0.37.0/scrape/scrape.go:592 +0xa1e
```

**Comment by schmikei** [comment]
Submitted and issue and PR to hopefully unblock this, will follow up soon! https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13905

**Comment by schmikei** [comment]
@sophieyfang mind updating your PR to latest main since https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector/pull/119 was merged? Was able to validate third party integrations via this draft https://github.com/GoogleCloudPlatform/ops-agent/pull/830

**Comment by schmikei** [comment]
Sorry for the inconvenience, but figured I'd chime in since I noticed, the latest operations-collector has breaking postgres changes that are being addressed in #804 relating to resource attributes needing to be flattened. 

If you want this unblocked I think that the commit `b564f3ae5dfe42d61c80a411a5474c31d6aa5c8a` should work 😄

**Review by qingling128 — APPROVED** [review]
LGTM

**Comment by sophieyfang** [comment]
> Sorry for the inconvenience, but figured I'd chime in since I noticed, the latest operations-collector has breaking postgres changes that are being addressed in #804 relating to resource attributes needing to be flattened.

No worries! 🐶
Since your PR https://github.com/GoogleCloudPlatform/ops-agent/pull/804 will probably fix it. Thus i will just merge this PR in first. WDYT?

**Comment by schmikei** [comment]
> No worries! 🐶 Since your PR #804 will probably fix it. Thus i will just merge this PR in first. WDYT?

Would prefer to not have anything broken but depends on the timeline of when #804 can be merged. It is currently blocked until https://github.com/GoogleCloudPlatform/ops-agent/pull/836 gets merged and the changes can be isolated. I believe everything should be good to merge but don't like things being in a broken state even if only intermittently. As a side note, if the postgres one gets in, then it should essentially

**Comment by qingling128** [comment]
`Ops Agent integration test (Windows)` failed for aother known issue we are investigating b/240564518

`third party apps integration test (Buster)` failed for another know issue that is being fixed by https://github.com/GoogleCloudPlatform/ops-agent/pull/836

**Pull request merged**
