### PR TITLE
fix:Update to use [:upper:] [:lower:] to support accents and foreign alphabets

### PR DESCRIPTION
**Pull request by bluPhy**
…alphabets

Update to use [:upper:] [:lower:] to support accents and foreign alphabets. The output from lsb_release most likely never produce non-ASCII characters but as a matter of best practice I propose to change it.

### CODE REVIEW

**Comment by qingling128** [comment]
In fact, on a second thought, all the build VMs we use today to build the agent comes with English by default. So this change might be a noop.

**Comment by qingling128** [comment]
The integration tests passed before:
image

Merging

**Review by qingling128 — APPROVED** [review]
LGTM

**Comment by igorpeshansky** [comment]
This change is a no-op; everyone else seems to assume that `/etc/lsb-release` will contain ASCII data (in fact, the Python implementation uses the `ascii` codec for everything: https://lists.debian.org/debian-lsb/2012/06/msg00000.html).

**Pull request merged**
