### PR TITLE
OTel parse_json preserves fields

### PR DESCRIPTION
**Pull request by jefferbrecht**
## Checklist:
- Unit tests
  - [ ] Unit tests do not apply.
  - [ ] Unit tests have been added/modified and passed for this PR.
- Integration tests
  - [ ] Integration tests do not apply.
  - [ ] Integration tests have been added/modified and passed for this PR.
- Documentation
  - [ ] This PR introduces no user visible changes.
  - [ ] This PR introduces user visible changes and the corresponding documentation change has been made.
- Minor version bump
  - [ ] This PR introduces no new features.
  - [ ] This PR introduces new features, and there is a separate PR to bump the [minor version](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/VERSION) since the last [release](https://github.com/GoogleCloudPlatform/ops-agent/releases) already.
  - [ ] This PR bumps the version.

### CODE REVIEW

**Review by avilevy18 — APPROVED** [review]

**Review by quentinmit — COMMENTED** [review]
The existing behavior matches Fluent Bit's default. We can't just turn this on without causing backwards incompatible changes. (See `Reserve_Data` at https://docs.fluentbit.io/manual/v/1.3/filter/parser)

Do we want to add config for this? Change the default for both OTel and Fluent Bit despite the backwards-incompatible-ness?

**Comment by jefferbrecht** [comment]
> The existing behavior matches Fluent Bit's default. We can't just turn this on without causing backwards incompatible changes. (See `Reserve_Data` at https://docs.fluentbit.io/manual/v/1.3/filter/parser)
> 
> Do we want to add config for this? Change the default for both OTel and Fluent Bit despite the backwards-incompatible-ness?

We set `Reserve_Data` to true in the Ops Agent; the goal of this PR is to replicate that with OTel.

**Comment by quentinmit** [comment]
> > The existing behavior matches Fluent Bit's default. We can't just turn this on without causing backwards incompatible changes. (See `Reserve_Data` at https://docs.fluentbit.io/manual/v/1.3/filter/parser)
> > Do we want to add config for this? Change the default for both OTel and Fluent Bit despite the backwards-incompatible-ness?
> 
> We set `Reserve_Data` to `true` in the Ops Agent; the goal of this PR is to replicate that with OTel.

That appears to have been added in 2022 in 7eb301b54b. I don't see any discussion of the fact that that change was backwards-incompatible on that commit/PR... I guess we've already caused the pain at this point, so we might as well make OTel match?

**Review by quentinmit — APPROVED** [review]
LGTM since we seem to have already decided we're okay with this backwards-incompatible change.

**Comment by jefferbrecht** [comment]
Test failure unrelated, merging.

**Pull request merged**
