### PR TITLE
Redirect info log messages to stdout.

### PR DESCRIPTION
**Pull request by igorpeshansky**
Fixes b/191809260.

### CODE REVIEW

**Comment by punya** [comment]
The code looks good, but why do we want to do this?

**Comment by qingling128** [comment]
> The code looks good, but why do we want to do this?

There was a customer issue reported via an email. (b/191809260 is the tracking bug.) Not a GA blocker, but looks like a low hanging fruit.

**Comment by igorpeshansky** [comment]
We should do it because PowerShell presents any messages sent to stderr as errors.

**Review by qingling128 — APPROVED** [review]
LGTM

**Pull request merged**
