### PR TITLE
Updated opentelemetry-operations-collector

### PR DESCRIPTION
**Pull request by braydonk**
This PR updates the opentelemetry-operations-collector submodule to the latest version. The motivation is to include the new log spam filtering functionality.

### CODE REVIEW

**Comment by qingling128** [comment]
BTW looking at the diff, there are 2 commits that upgraded the upstream collector version and come with some risks:

image

So we should probably merge this one after release `2.7.1` is out (It's being released now).

**Review by qingling128 — APPROVED** [review]
LGTM, modulo the integration tests pass.

**Review by quentinmit — APPROVED** [review]

**Comment by qingling128** [comment]
This one might be obsolete now.

**Comment by braydonk** [comment]
Yes, it is obsolete now that #307 is merged.

**Pull request closed without merging**
